//Khoi tao danh sach san pham
function createProduct() {
    localStorage.clear();
    if (localStorage.getItem('products') == null) {
        let products = [
        {
            id: 1,
            status: 1, 
            title: 'Cô dâu lung linh',
            img: './assets/img/products/DAM_CUOI_01-00.jpg',
            img01: './assets/img/products/DAM_CUOI_01-01.jpg',
            img02: './assets/img/products/DAM_CUOI_01-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 2,
            status: 1, 
            title: 'Cô dâu quyến rũ',
            img: './assets/img/products/DAM_CUOI_02-00.jpg',
            img01: './assets/img/products/DAM_CUOI_02-01.jpg',
            img02: './assets/img/products/DAM_CUOI_02-02.jpg',
            img03: './assets/img/products/DAM_CUOI_02-03.jpg',
            img04: './assets/img/products/DAM_CUOI_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 3,
            status: 1, 
            title: 'Mẫu ảnh cuốn hút',
            img: './assets/img/products/MAU_ANH_01-00.jpg',
            img01: './assets/img/products/MAU_ANH_01-01.jpg',
            img02: './assets/img/products/MAU_ANH_01-02jpg',
            img03: './assets/img/products/MAU_ANH_01-03.jpg',
            img04: './assets/img/products/MAU_ANH_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 4,
            status: 1, title: 'Giao diện đi chơi siêu xịn',
            img: './assets/img/products/DI_TIEC_DI_CHOI_01-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_01-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_01-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_01-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 5,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_03-00.jpg',
            img01: './assets/img/products/DAM_CUOI_03-01.jpg',
            img02: './assets/img/products/DAM_CUOI_03-02.jpg',
            img03: './assets/img/products/DAM_CUOI_03-03.jpg',
            img04: './assets/img/products/DAM_CUOI_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 6,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_02-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_02-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_02-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_02-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },

        {
            id: 7,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_04-00.jpg',
            img01: './assets/img/products/DAM_CUOI_04-01.jpg',
            img02: './assets/img/products/DAM_CUOI_04-02.jpg',
            img03: './assets/img/products/DAM_CUOI_04-03.jpg',
            img04: './assets/img/products/DAM_CUOI_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 8,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_05-00.jpg',
            img01: './assets/img/products/DAM_CUOI_05-01.jpg',
            img02: './assets/img/products/DAM_CUOI_05-02.jpg',
            img03: './assets/img/products/DAM_CUOI_05-03.jpg',
            img04: './assets/img/products/DAM_CUOI_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 9,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_06-00.jpg',
            img01: './assets/img/products/DAM_CUOI_06-01.jpg',
            img02: './assets/img/products/DAM_CUOI_06-02.jpg',
            img03: './assets/img/products/DAM_CUOI_06-03.jpg',
            img04: './assets/img/products/DAM_CUOI_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 10,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_07-00.jpg',
            img01: './assets/img/products/DAM_CUOI_07-01.jpg',
            img02: './assets/img/products/DAM_CUOI_07-02.jpg',
            img03: './assets/img/products/DAM_CUOI_07-03.jpg',
            img04: './assets/img/products/DAM_CUOI_07-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 11,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_08-00.jpg',
            img01: './assets/img/products/DAM_CUOI_08-01.jpg',
            img02: './assets/img/products/DAM_CUOI_08-02.jpg',
            img03: './assets/img/products/DAM_CUOI_08-03.jpg',
            img04: './assets/img/products/DAM_CUOI_08-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 12,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_09-00.jpg',
            img01: './assets/img/products/DAM_CUOI_09-01.jpg',
            img02: './assets/img/products/DAM_CUOI_09-02.jpg',
            img03: './assets/img/products/DAM_CUOI_09-03.jpg',
            img04: './assets/img/products/DAM_CUOI_09-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 13,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_10-00.jpg',
            img01: './assets/img/products/DAM_CUOI_10-01.jpg',
            img02: './assets/img/products/DAM_CUOI_10-02.jpg',
            img03: './assets/img/products/DAM_CUOI_10-03.jpg',
            img04: './assets/img/products/DAM_CUOI_10-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 14,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_03-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_03-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_03-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_03-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 15,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_04-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_04-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_04-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_04-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 16,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_01-00.jpg',
            img01: './assets/img/products/KY_YEU_01-01.jpg',
            img02: './assets/img/products/KY_YEU_01-02.jpg',
            img03: './assets/img/products/KY_YEU_01-03.jpg',
            img04: './assets/img/products/KY_YEU_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 17,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_02-00.jpg',
            img01: './assets/img/products/KY_YEU_02-01.jpg',
            img02: './assets/img/products/KY_YEU_02-02.jpg',
            img03: './assets/img/products/KY_YEU_02-03.jpg',
            img04: './assets/img/products/KY_YEU_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 18,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_03-00.jpg',
            img01: './assets/img/products/KY_YEU_03-01.jpg',
            img02: './assets/img/products/KY_YEU_03-02.jpg',
            img03: './assets/img/products/KY_YEU_03-03.jpg',
            img04: './assets/img/products/KY_YEU_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 19,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_04-00.jpg',
            img01: './assets/img/products/KY_YEU_04-01.jpg',
            img02: './assets/img/products/KY_YEU_04-02.jpg',
            img03: './assets/img/products/KY_YEU_04-03.jpg',
            img04: './assets/img/products/KY_YEU_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 20,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_02-00.jpg',
            img01: './assets/img/products/MAU_ANH_02-01.jpg',
            img02: './assets/img/products/MAU_ANH_02-02.jpg',
            img03: './assets/img/products/MAU_ANH_02-03.jpg',
            img04: './assets/img/products/MAU_ANH_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 21,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_03-00.jpg',
            img01: './assets/img/products/MAU_ANH_03-01.jpg',
            img02: './assets/img/products/MAU_ANH_03-02.jpg',
            img03: './assets/img/products/MAU_ANH_03-03.jpg',
            img04: './assets/img/products/MAU_ANH_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 22,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_04-00.jpg',
            img01: './assets/img/products/MAU_ANH_04-01.jpg',
            img02: './assets/img/products/MAU_ANH_04-02.jpg',
            img03: './assets/img/products/MAU_ANH_04-03.jpg',
            img04: './assets/img/products/MAU_ANH_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 23,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_05-00.jpg',
            img01: './assets/img/products/MAU_ANH_05-01.jpg',
            img02: './assets/img/products/MAU_ANH_05-02.jpg',
            img03: './assets/img/products/MAU_ANH_05-03.jpg',
            img04: './assets/img/products/MAU_ANH_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 24,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_06-00.jpg',
            img01: './assets/img/products/MAU_ANH_06-01.jpg',
            img02: './assets/img/products/MAU_ANH_06-02.jpg',
            img03: './assets/img/products/MAU_ANH_06-03.jpg',
            img04: './assets/img/products/MAU_ANH_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 25,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_07-00.jpg',
            img01: './assets/img/products/MAU_ANH_07-01.jpg',
            img02: './assets/img/products/MAU_ANH_07-02.jpg',
            img03: './assets/img/products/MAU_ANH_07-03.jpg',
            img04: './assets/img/products/MAU_ANH_07-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 26,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_08-00.jpg',
            img01: './assets/img/products/MAU_ANH_08-01.jpg',
            img02: './assets/img/products/MAU_ANH_08-02.jpg',
            img03: './assets/img/products/MAU_ANH_08-03.jpg',
            img04: './assets/img/products/MAU_ANH_08-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 27,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_09-00.jpg',
            img01: './assets/img/products/MAU_ANH_09-01.jpg',
            img02: './assets/img/products/MAU_ANH_09-02.jpg',
            img03: './assets/img/products/MAU_ANH_09-03.jpg',
            img04: './assets/img/products/MAU_ANH_09-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 28,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_10-00.jpg',
            img01: './assets/img/products/MAU_ANH_10-01.jpg',
            img02: './assets/img/products/MAU_ANH_10-02.jpg',
            img03: './assets/img/products/MAU_ANH_10-03.jpg',
            img04: './assets/img/products/MAU_ANH_10-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 29,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_11-00.jpg',
            img01: './assets/img/products/MAU_ANH_11-01.jpg',
            img02: './assets/img/products/MAU_ANH_11-02.jpg',
            img03: './assets/img/products/MAU_ANH_11-03.jpg',
            img04: './assets/img/products/MAU_ANH_11-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 30,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_12-00.jpg',
            img01: './assets/img/products/MAU_ANH_12-01.jpg',
            img02: './assets/img/products/MAU_ANH_12-02.jpg',
            img03: './assets/img/products/MAU_ANH_12-03.jpg',
            img04: './assets/img/products/MAU_ANH_12-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 31,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_13-00.jpg',
            img01: './assets/img/products/MAU_ANH_13-01.jpg',
            img02: './assets/img/products/MAU_ANH_13-02.jpg',
            img03: './assets/img/products/MAU_ANH_13-03.jpg',
            img04: './assets/img/products/MAU_ANH_13-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 32,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_14-00.jpg',
            img01: './assets/img/products/MAU_ANH_14-01.jpg',
            img02: './assets/img/products/MAU_ANH_14-02.jpg',
            img03: './assets/img/products/MAU_ANH_14-03.jpg',
            img04: './assets/img/products/MAU_ANH_14-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 33,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_15-00.jpg',
            img01: './assets/img/products/MAU_ANH_15-01.jpg',
            img02: './assets/img/products/MAU_ANH_15-02.jpg',
            img03: './assets/img/products/MAU_ANH_15-03.jpg',
            img04: './assets/img/products/MAU_ANH_15-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 34,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_16-00.jpg',
            img01: './assets/img/products/MAU_ANH_16-01.jpg',
            img02: './assets/img/products/MAU_ANH_16-02.jpg',
            img03: './assets/img/products/MAU_ANH_16-03.jpg',
            img04: './assets/img/products/MAU_ANH_16-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 35,
            status: 1, 
            title: 'Nạc nọng heo nướng kèm xôi trắng (500gr)',
            category: 'Món mặn',
            img: './assets/img/products/nac-nong-heo-nuong-kem-xoi-trang.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Nọng heo - phần thịt ngon nhất trên thủ heo, với những dải thịt nạc mỡ đan xen, mỗi thủ chỉ có được 1-2kg thịt nọng ngon mềm như vậy. Bếp trưởng Bếp Hoa tẩm ướp thật ngấm gia vị, nướng thẳng trên than hoa thơm nức, xém cạnh đẹp mắt. Miếng thịt nướng xong gắp khỏi vỉ vẫn thấy mỡ thơm còn sôi trên dải thịt, để thịt nghỉ vài phút khi thái ra óng ánh nước, gắp miếng thịt chấm với nước sốt siêu ngon độc quyền của Bếp, ngon đến tứa nước miếng, tranh nhau gắp sạch đĩa'
        },

        {
            id: 36,
            status: 1, 
            title: 'Thịt quay (400gr)',
            category: 'Món mặn',
            img: './assets/img/products/thit-quay.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Thịt lợn quay thơm mùi lá mắc mật. Ngoài bì giòn rụm, thịt bên trong mềm, hương vị đậm đà. Đặc biệt, bếp có loại sốt chấm thịt được pha bằng công thức riêng biệt chỉ Bếp Hoa mới có.Hướng dẫn sử dụng: Sử dụng ngay trong ngày. Bảo quản trong tủ mát.'
        },

        {
            id: 37,
            status: 1, 
            title: 'Khâu nhục',
            category: 'Món mặn',
            img: './assets/img/products/khau-nhuc.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Khâu nhục - món ăn cầu kỳ mang phong vị phương Bắc. Làm từ thịt lợn ta, khâu khục được hấp cách thủy trong 6 tiếng cùng với rất nhiều loại gia vị. Thịt mềm nhừ, ngọt vị, phần bì trong và dẻo quẹo. Mỡ ngậy ngậy tan chảy ngay khi vừa đưa lên miệng. Hướng dẫn bảo quản: Hâm nóng lại bằng nồi hấp cách thủy hoặc lò vi sóng. Bảo quản trong tủ mát từ 3-5 ngày.'
        },
        {
            id: 38,
            status: 1, 
            title: 'Xíu mại tôm thịt ( 10 viên)',
            category: 'Món mặn',
            img: './assets/img/products/ha_cao_tom_thit.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Những miếng há cảo, sủi cảo, hoành thánh với phần nhân tôm, sò điệp, hải sản tươi ngon hay nhân thịt heo thơm ngậy chắc chắn sẽ khiến bất kỳ ai thưởng thức đều cảm thấy rất ngon miệng.'
        },
        {
            id: 39,
            status: 1, 
            title: 'Chè hương cốm lá dứa',
            category: 'Món tráng miệng',
            img: './assets/img/products/che-com-la-dua.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Chè cốm hương lá dứa dẻo thơm, ngọt dịu, từng hạt cốm thoảng thoảng đâu đó hương lá dứa mát lành'
        },

        {
            id: 40,
            status: 1, 
            title: 'Bánh bông lan chanh dây',
            category: 'Món tráng miệng',
            img: './assets/img/products/banh-bong-lan-chanh-day.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Bánh bông lan chanh dây với vị chua nhẹ, không bị ngọt gắt hẳn sẽ là sự lựa chọn hoàn hảo'
        },

        {
            id: 41,
            status: 1, 
            title: 'Chè bưởi',
            category: 'Món tráng miệng',
            img: './assets/img/products/che-buoi.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Chè bưởi rất dễ ăn bởi hương vị ngọt mát, thơm ngon, vị bùi bùi của đậu xanh, giòn sần sật của cùi bưởi mà không hề bị đắng'
        },
        {
            id: 42,
            status: 1, 
            title: 'Set lẩu Thái tomyum',
            category: "Món lẩu",
            img: './assets/img/products/lau-thai-tomyum.jpeg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Lẩu Thái là món ăn xuất phát từ món canh chua Tom yum nổi tiếng của Thái Lan. Nước lẩu có hương vị chua chua cay cay đặc trưng. Các món nhúng lẩu gồn thịt bò, hải sản, rau xanh và các loại nấm.',
        },
        {
            id: 43,
            status: 1, 
            title: 'Set lẩu Thái nấm chay',
            category: "Món lẩu",
            img: './assets/img/products/lau-thai-nam-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Một set lẩu Thái nấm chay với nước dùng 100% từ rau củ quả tự nhiên, thêm sả cây tươi, riềng miếng, ớt, nước dừa để lên được vị nước lẩu Thái chuẩn vị. Đồ nhúng đa dạng với nhiều loại nấm khác nhau, rau tươi giòn, đậu phụ mềm xốp, váng đậu amla chiên giòn. Kèm bún tươi ăn rất hợp.',
        },
        {
            id: 44,
            status: 1, 
            title: 'Đậu hũ xào nấm chay',
            category: "Món chay",
            img: './assets/img/products/dau-hu-xao-nam-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Món xào thanh nhẹ ngọt lịm từ rau củ và nấm tươi, thêm chút đậu phụ chiên thái miếng, nêm nếm đậm đà. Ăn kèm cơm trắng hay làm bún trộn rau củ cũng rất hợp.',
        },
        {
            id: 45,
            status: 1, 
            title: 'Bún trộn chay (1 suất)',
            category: "Món chay",
            img: './assets/img/products/bun-tron-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Bún trộn chay tưởng là quen mà ăn ngon lạ miệng. Với bún tươi được trộn với nước tương và sốt ớt đặc biệt, mắm chay thơm, thêm rau củ tươi, rau thơm bắt vị, nấm xào săn, đậu phụ thái lát, một món thanh nhẹ thích hợp ăn trưa hoặc để dành cho anh chị eat-clean bữa tối.',
        },
        {
            id: 46,
            status: 1, 
            title: 'Bún riêu chay (1 suất)',
            category: "Món chay",
            img: './assets/img/products/bun-rieu-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Bún riêu chay với phần gạch cua chay từ đậu phụ non mềm đánh với sốt màu thơm ngon. Nước dùng thanh nhẹ từ rau củ quả, được nấu lên vị đậm đà rất ngon miệng. Một phần bún riêu kèm với gạch cua là giò chay, đậu phụ rán, rau sống ngọt giòn và tương ớt chay sánh ngon.',
        },
        {
            id: 47,
            status: 1, 
            title: 'Miến xào rau củ chay',
            category: "Món chay",
            img: './assets/img/products/mien-xao-rau-cu-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Sợi miến khoai lang bếp ngâm cho mềm, xào kèm rau củ quả tươi theo mùa, nêm cùng nước tương và dầu mè, một món xào chay vừa mát lành lại thơm ngon.',
        },
        {
            id: 48,
            status: 1, 
            title: 'Cuốn nấm chay (10 cuốn)',
            category: "Món chay",
            img: './assets/img/products/cuon-nam-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Nấm tươi làm chín cuộn với bánh phở và rau bào, thêm đậu phụ chiên giòn thái chân hương đưa vị, chấm mắm chua ngọt chay bếp trưởng pha chế, một món ngon làm món khai vị rất hợp.',
        },
        {
            id: 49,
            status: 1, 
            title: 'Xôi xéo',
            category: "Món chay",
            img: './assets/img/products/xoi-xeo.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Xôi xéo đậu xanh bếp dùng nếp cái hoa vàng hạt mẩy, ngâm với nước nghệ và đồ 2 lần cho hạt nếp chín mềm và thơm, đậu xanh sên mịn cắt tơi trộn cùng xôi, khi ăn rắc hành phi đưa vị, rất hấp dẫn.',
        },
        {
            id: 50,
            status: 1, 
            title: 'Chả quế chay',
            category: "Món chay",
            img: './assets/img/products/cha-que-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: '',
        },
        {
            id: 51,
            status: 1, 
            title: 'Nem chay',
            category: "Món chay",
            img: './assets/img/products/nem-chay.png',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Nem chay thơm ngon, thanh thuần bếp trưởng sử dụng rau củ bào tươi, đậu xanh, khoai môn, miến, mộc nhĩ và nấm hương, tất cả xào thơm cho lên vị, sau đó cuộn với bánh đa nem mỏng, chiên giòn vỏ, chấm mắm chua ngọt chay ăn kèm rau thơm rất hấp dẫn.',
        },
        {
            id: 52,
            status: 1, 
            title: 'Bánh tráng trộn',
            category: "Món ăn vặt",
            img: './assets/img/products/banh-trang-tron.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Bánh tráng trộn là món ăn ngon không chỉ nổi danh đất Sài Thành mà ngay khi xuất hiện tại Hà Nội, nó cũng đã trở thành món ăn “hot trend” rất được giới trẻ yêu thích. ',
        },
        {
            id: 53,
            status: 1, 
            title: 'Bánh tráng nướng',
            category: "Món ăn vặt",
            img: './assets/img/products/banh-trang-nuong.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Khác với món bánh tráng trộn, bánh tráng nướng được phết một lớp trứng chút lên bề mặt bánh tráng cùng thịt băm, mỡ hành, nướng đến khi có màu vàng ruộm. ',
        },
        {
            id: 54,
            status: 1, 
            title: 'Ốc thập cẩm (1 suất)',
            category: "Món ăn vặt",
            img: './assets/img/products/oc-thap-cam.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Được chế biến đủ các món ốc ngon khác nhau, như: ốc hấp, ốc luộc, ốc xào, ốc bỏ lò,.. với đủ các gia vị như tỏi, hành, ớt, tiêu, rau răm,…',
        },
        {
            id: 55,
            status: 1, 
            title: 'Cơm cháy chà bông',
            category: "Món ăn vặt",
            img: './assets/img/products/com-chay-cha-bong.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Cơm cháy chà bông có thể bảo quản cả tháng mà ăn vẫn ngon và đóng gói rất tiện.',
        },
        {
            id: 56,
            status: 1, 
            title: 'Phá lấu (1 suất)',
            category: "Món ăn vặt",
            img: './assets/img/products/pha-lau.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Cứ mỗi lần hỏi “Ăn gì ở Sài Gòn ngon, rẻ ?” là người ta nhớ ngay món phá lấu.',
        },
        {
            id: 57,
            status: 1, 
            title: 'Bột chiên (1 suất)',
            category: "Món ăn vặt",
            img: './assets/img/products/bot-chien.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Cùng với nước chấm đặc biệt, bột chiên để lại hương vị khó tả cho thực khách sau khi thưởng thức.',
        },
        {
            id: 58,
            status: 1, 
            title: 'Gỏi khô bò (1 suất)',
            category: "Món ăn vặt",
            img: './assets/img/products/goi-bo-kho.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: 'Món mặn',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Thơm ngon đến từng sợi bò.',
        },
        {
            id: 59,
            status: 1, 
            title: 'Hoành thánh tôm (10 viên)',
            img: './assets/img/products/hoanh_thanh.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: '',
            MUA: '',
            price: 500000,
            desc: 'Những miếng há cảo, sủi cảo, hoành thánh với phần nhân tôm, sò điệp, hải sản tươi ngon hay nhân thịt heo thơm ngậy chắc chắn sẽ khiến bất kỳ ai thưởng thức đều cảm thấy rất ngon miệng.'
        },
        {
            id: 60,
            status: 1, 
            title: 'Nước ép dâu tây',
            img: './assets/img/products/nuoc-ep-dau-tay.jpg',
            img01: './assets/img/products/nam-dui-ga-chay-toi-01.jpeg',
            img02: './assets/img/products/nam-dui-ga-chay-toi-02.jpeg',
            img03: './assets/img/products/nam-dui-ga-chay-toi-03.jpeg',
            img04: './assets/img/products/nam-dui-ga-chay-toi-04.jpeg',
            img05: './assets/img/products/nam-dui-ga-chay-toi-05.jpeg',
            img06: './assets/img/products/nam-dui-ga-chay-toi-06.jpeg',
            img07: './assets/img/products/nam-dui-ga-chay-toi-07.jpeg',
            img08: './assets/img/products/nam-dui-ga-chay-toi-08.jpeg',
            img09: './assets/img/products/nam-dui-ga-chay-toi-09.jpeg',
            img10: './assets/img/products/nam-dui-ga-chay-toi-10.jpeg',
            category: '',
            MUA: '',
            price: 500000,
            desc: 'Dâu tây ăn nguyên quả ngon ngọt, có cả quả dôn dốt chua, màu đỏ mọng trông cực yêu. Không chỉ ngon miệng mà đồ uống từ dâu tây còn có công dụng bảo vệ sức khỏe, sáng mắt, đẹp da, thon gọn vóc dáng. Làm giảm nguy cơ mắc bệnh về mỡ máu, chống viêm,…'
        },
        ]
        localStorage.setItem('products', JSON.stringify(products));
    }
}

// Create admin account 
function createAdminAccount() {
    let accounts = localStorage.getItem("accounts");
    if (!accounts) {
        accounts = [];
        accounts.push({
            fullname: "Hoàng Gia Bảo",
            phone: "hgbaodev",
            password: "123456",
            address: 'https://github.com/hgbaodev',
            email: 'musicanime2501@gmail.com',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        accounts.push({
            fullname: "Trần Nhật Sinh",
            phone: "0123456789",
            password: "123456",
            address: '',
            email: '',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        localStorage.setItem('accounts', JSON.stringify(accounts));
    }
}

window.onload = createProduct();
window.onload = createAdminAccount();