//Khoi tao danh sach san pham
function createProduct() {
    localStorage.clear();
    if (localStorage.getItem('products') == null) {
        let products = [
        {
            id: 1,
            status: 1, 
            title: 'Cô dâu lung linh',
            img: './assets/img/products/DAM_CUOI_01-00.jpg',
            img01: './assets/img/products/DAM_CUOI_01-01.jpg',
            img02: './assets/img/products/DAM_CUOI_01-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 2,
            status: 1, 
            title: 'Cô dâu quyến rũ',
            img: './assets/img/products/DAM_CUOI_02-00.jpg',
            img01: './assets/img/products/DAM_CUOI_02-01.jpg',
            img02: './assets/img/products/DAM_CUOI_02-02.jpg',
            img03: './assets/img/products/DAM_CUOI_02-03.jpg',
            img04: './assets/img/products/DAM_CUOI_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 3,
            status: 1, 
            title: 'Mẫu ảnh cuốn hút',
            img: './assets/img/products/MAU_ANH_01-00.jpg',
            img01: './assets/img/products/MAU_ANH_01-01.jpg',
            img02: './assets/img/products/MAU_ANH_01-02jpg',
            img03: './assets/img/products/MAU_ANH_01-03.jpg',
            img04: './assets/img/products/MAU_ANH_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 4,
            status: 1, title: 'Giao diện đi chơi siêu xịn',
            img: './assets/img/products/DI_TIEC_DI_CHOI_01-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_01-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_01-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_01-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            video: './assets/video/DI_TIEC_DI_CHOI_01.mp4',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 5,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_03-00.jpg',
            img01: './assets/img/products/DAM_CUOI_03-01.jpg',
            img02: './assets/img/products/DAM_CUOI_03-02.jpg',
            img03: './assets/img/products/DAM_CUOI_03-03.jpg',
            img04: './assets/img/products/DAM_CUOI_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 6,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_02-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_02-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_02-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_02-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },

        {
            id: 7,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_04-00.jpg',
            img01: './assets/img/products/DAM_CUOI_04-01.jpg',
            img02: './assets/img/products/DAM_CUOI_04-02.jpg',
            img03: './assets/img/products/DAM_CUOI_04-03.jpg',
            img04: './assets/img/products/DAM_CUOI_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            video: './assets/video/DAM_CUOI_04.mp4',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 8,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_05-00.jpg',
            img01: './assets/img/products/DAM_CUOI_05-01.jpg',
            img02: './assets/img/products/DAM_CUOI_05-02.jpg',
            img03: './assets/img/products/DAM_CUOI_05-03.jpg',
            img04: './assets/img/products/DAM_CUOI_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 9,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_06-00.jpg',
            img01: './assets/img/products/DAM_CUOI_06-01.jpg',
            img02: './assets/img/products/DAM_CUOI_06-02.jpg',
            img03: './assets/img/products/DAM_CUOI_06-03.jpg',
            img04: './assets/img/products/DAM_CUOI_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 10,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_07-00.jpg',
            img01: './assets/img/products/DAM_CUOI_07-01.jpg',
            img02: './assets/img/products/DAM_CUOI_07-02.jpg',
            img03: './assets/img/products/DAM_CUOI_07-03.jpg',
            img04: './assets/img/products/DAM_CUOI_07-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 11,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_08-00.jpg',
            img01: './assets/img/products/DAM_CUOI_08-01.jpg',
            img02: './assets/img/products/DAM_CUOI_08-02.jpg',
            img03: './assets/img/products/DAM_CUOI_08-03.jpg',
            img04: './assets/img/products/DAM_CUOI_08-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 12,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_09-00.jpg',
            img01: './assets/img/products/DAM_CUOI_09-01.jpg',
            img02: './assets/img/products/DAM_CUOI_09-02.jpg',
            img03: './assets/img/products/DAM_CUOI_09-03.jpg',
            img04: './assets/img/products/DAM_CUOI_09-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },
        {
            id: 13,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_10-00.jpg',
            img01: './assets/img/products/DAM_CUOI_10-01.jpg',
            img02: './assets/img/products/DAM_CUOI_10-02.jpg',
            img03: './assets/img/products/DAM_CUOI_10-03.jpg',
            img04: './assets/img/products/DAM_CUOI_10-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 14,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_03-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_03-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_03-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_03-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 15,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_04-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_04-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_04-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_04-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },
        {
            id: 16,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_01-00.jpg',
            img01: './assets/img/products/KY_YEU_01-01.jpg',
            img02: './assets/img/products/KY_YEU_01-02.jpg',
            img03: './assets/img/products/KY_YEU_01-03.jpg',
            img04: './assets/img/products/KY_YEU_01-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 17,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_02-00.jpg',
            img01: './assets/img/products/KY_YEU_02-01.jpg',
            img02: './assets/img/products/KY_YEU_02-02.jpg',
            img03: './assets/img/products/KY_YEU_02-03.jpg',
            img04: './assets/img/products/KY_YEU_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 18,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_03-00.jpg',
            img01: './assets/img/products/KY_YEU_03-01.jpg',
            img02: './assets/img/products/KY_YEU_03-02.jpg',
            img03: './assets/img/products/KY_YEU_03-03.jpg',
            img04: './assets/img/products/KY_YEU_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 19,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_04-00.jpg',
            img01: './assets/img/products/KY_YEU_04-01.jpg',
            img02: './assets/img/products/KY_YEU_04-02.jpg',
            img03: './assets/img/products/KY_YEU_04-03.jpg',
            img04: './assets/img/products/KY_YEU_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        {
            id: 20,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_02-00.jpg',
            img01: './assets/img/products/MAU_ANH_02-01.jpg',
            img02: './assets/img/products/MAU_ANH_02-02.jpg',
            img03: './assets/img/products/MAU_ANH_02-03.jpg',
            img04: './assets/img/products/MAU_ANH_02-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 21,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_03-00.jpg',
            img01: './assets/img/products/MAU_ANH_03-01.jpg',
            img02: './assets/img/products/MAU_ANH_03-02.jpg',
            img03: './assets/img/products/MAU_ANH_03-03.jpg',
            img04: './assets/img/products/MAU_ANH_03-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 22,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_04-00.jpg',
            img01: './assets/img/products/MAU_ANH_04-01.jpg',
            img02: './assets/img/products/MAU_ANH_04-02.jpg',
            img03: './assets/img/products/MAU_ANH_04-03.jpg',
            img04: './assets/img/products/MAU_ANH_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 23,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_05-00.jpg',
            img01: './assets/img/products/MAU_ANH_05-01.jpg',
            img02: './assets/img/products/MAU_ANH_05-02.jpg',
            img03: './assets/img/products/MAU_ANH_05-03.jpg',
            img04: './assets/img/products/MAU_ANH_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 24,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_06-00.jpg',
            img01: './assets/img/products/MAU_ANH_06-01.jpg',
            img02: './assets/img/products/MAU_ANH_06-02.jpg',
            img03: './assets/img/products/MAU_ANH_06-03.jpg',
            img04: './assets/img/products/MAU_ANH_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        {
            id: 25,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_07-00.jpg',
            img01: './assets/img/products/MAU_ANH_07-01.jpg',
            img02: './assets/img/products/MAU_ANH_07-02.jpg',
            img03: './assets/img/products/MAU_ANH_07-03.jpg',
            img04: './assets/img/products/MAU_ANH_07-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 26,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_08-00.jpg',
            img01: './assets/img/products/MAU_ANH_08-01.jpg',
            img02: './assets/img/products/MAU_ANH_08-02.jpg',
            img03: './assets/img/products/MAU_ANH_08-03.jpg',
            img04: './assets/img/products/MAU_ANH_08-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 27,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_09-00.jpg',
            img01: './assets/img/products/MAU_ANH_09-01.jpg',
            img02: './assets/img/products/MAU_ANH_09-02.jpg',
            img03: './assets/img/products/MAU_ANH_09-03.jpg',
            img04: './assets/img/products/MAU_ANH_09-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 28,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_10-00.jpg',
            img01: './assets/img/products/MAU_ANH_10-01.jpg',
            img02: './assets/img/products/MAU_ANH_10-02.jpg',
            img03: './assets/img/products/MAU_ANH_10-03.jpg',
            img04: './assets/img/products/MAU_ANH_10-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 29,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_11-00.jpg',
            img01: './assets/img/products/MAU_ANH_11-01.jpg',
            img02: './assets/img/products/MAU_ANH_11-02.jpg',
            img03: './assets/img/products/MAU_ANH_11-03.jpg',
            img04: './assets/img/products/MAU_ANH_11-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 30,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_12-00.jpg',
            img01: './assets/img/products/MAU_ANH_12-01.jpg',
            img02: './assets/img/products/MAU_ANH_12-02.jpg',
            img03: './assets/img/products/MAU_ANH_12-03.jpg',
            img04: './assets/img/products/MAU_ANH_12-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 31,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_13-00.jpg',
            img01: './assets/img/products/MAU_ANH_13-01.jpg',
            img02: './assets/img/products/MAU_ANH_13-02.jpg',
            img03: './assets/img/products/MAU_ANH_13-03.jpg',
            img04: './assets/img/products/MAU_ANH_13-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            video: './assets/video/MAU_ANH_13.mp4',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 32,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_14-00.jpg',
            img01: './assets/img/products/MAU_ANH_14-01.jpg',
            img02: './assets/img/products/MAU_ANH_14-02.jpg',
            img03: './assets/img/products/MAU_ANH_14-03.jpg',
            img04: './assets/img/products/MAU_ANH_14-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 33,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_15-00.jpg',
            img01: './assets/img/products/MAU_ANH_15-01.jpg',
            img02: './assets/img/products/MAU_ANH_15-02.jpg',
            img03: './assets/img/products/MAU_ANH_15-03.jpg',
            img04: './assets/img/products/MAU_ANH_15-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 34,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_16-00.jpg',
            img01: './assets/img/products/MAU_ANH_16-01.jpg',
            img02: './assets/img/products/MAU_ANH_16-02.jpg',
            img03: './assets/img/products/MAU_ANH_16-03.jpg',
            img04: './assets/img/products/MAU_ANH_16-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 35,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_17-00.jpg',
            img01: './assets/img/products/MAU_ANH_17-01.jpg',
            img02: './assets/img/products/MAU_ANH_17-02.jpg',
            img03: './assets/img/products/MAU_ANH_17-03.jpg',
            img04: './assets/img/products/MAU_ANH_17-04.jpg',
            img05: './assets/img/products/MAU_ANH_17-05.jpg',
            img06: './assets/img/products/MAU_ANH_17-06.jpg',
            img07: './assets/img/products/MAU_ANH_17-07.jpg',
            img08: './assets/img/products/MAU_ANH_17-08.jpg',
            img09: './assets/img/products/MAU_ANH_17-09.jpg',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 36,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_01-00.jpg',
            img01: './assets/img/products/SU_KIEN_01-01.jpg',
            img02: './assets/img/products/SU_KIEN_01-02.jpg',
            img03: './assets/img/products/SU_KIEN_01-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 37,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_02-00.jpg',
            img01: './assets/img/products/SU_KIEN_02-01.jpg',
            img02: './assets/img/products/SU_KIEN_02-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 38,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_18-00.jpg',
            img01: './assets/img/products/MAU_ANH_18-01.jpg',
            img02: './assets/img/products/MAU_ANH_18-02.jpg',
            img03: './assets/img/products/MAU_ANH_18-03.jpg',
            img04: './assets/img/products/MAU_ANH_18-04.jpg',
            img05: './assets/img/products/MAU_ANH_18-05.jpg',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 39,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_19-00.jpg',
            img01: './assets/img/products/MAU_ANH_19-01.jpg',
            img02: './assets/img/products/MAU_ANH_19-02.jpg',
            img03: './assets/img/products/MAU_ANH_19-03.jpg',
            img04: './assets/img/products/MAU_ANH_19-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 40,
            status: 1, 
            title: 'Mẫu ảnh thời trang chuyên nghiệp',
            img: './assets/img/products/MAU_ANH_20-00.jpg',
            img01: './assets/img/products/MAU_ANH_20-01.jpg',
            img02: './assets/img/products/MAU_ANH_20-02.jpg',
            img03: './assets/img/products/MAU_ANH_20-03.jpg',
            img04: './assets/img/products/MAU_ANH_20-04.jpg',
            img05: './assets/img/products/MAU_ANH_20-05.jpg',
            img06: './assets/img/products/MAU_ANH_20-06.jpg',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 41,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_11-00.jpg',
            img01: './assets/img/products/DAM_CUOI_11-01.jpg',
            img02: './assets/img/products/DAM_CUOI_11-02.jpg',
            img03: './assets/img/products/DAM_CUOI_11-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 42,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_12-00.jpg',
            img01: './assets/img/products/DAM_CUOI_12-01.jpg',
            img02: './assets/img/products/DAM_CUOI_12-02.jpg',
            img03: './assets/img/products/DAM_CUOI_12-03.jpg',
            img04: './assets/img/products/DAM_CUOI_12-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 43,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_13-00.jpg',
            img01: './assets/img/products/DAM_CUOI_13-01.jpg',
            img02: './assets/img/products/DAM_CUOI_13-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 44,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_14-00.jpg',
            img01: './assets/img/products/DAM_CUOI_14-01.jpg',
            img02: './assets/img/products/DAM_CUOI_14-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 45,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_15-00.jpg',
            img01: './assets/img/products/DAM_CUOI_15-01.jpg',
            img02: './assets/img/products/DAM_CUOI_15-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 46,
            status: 1, 
            title: 'Cô dâu kiêu sa',
            img: './assets/img/products/DAM_CUOI_16-00.jpg',
            img01: './assets/img/products/DAM_CUOI_16-01.jpg',
            img02: './assets/img/products/DAM_CUOI_16-02.jpg',
            img03: '',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đám cưới',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm cô dâu siêu nhẹ nhàng, khởi đầu cho muôn vàn may mắn, lưu giữ khoảnh khắc thiên thần của thanh xuân. Nàng dâu vô cùng hài lòng, tự tin, tươi tắn.'
        },

        {
            id: 47,
            status: 1, 
            title: 'Giao diện du xuân ngất ngây',
            img: './assets/img/products/DI_TIEC_DI_CHOI_05-00.jpg',
            img01: './assets/img/products/DI_TIEC_DI_CHOI_05-01.jpg',
            img02: './assets/img/products/DI_TIEC_DI_CHOI_05-02.jpg',
            img03: './assets/img/products/DI_TIEC_DI_CHOI_05-03.jpg',
            img04: './assets/img/products/DI_TIEC_DI_CHOI_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Đi tiệc - Đi chơi',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm đi tiệc, đi chơi vô cùng ấn tượng, mang lại cảm giác tự nhiên. Makeup nhanh chóng tiện lợi cho các nàng năng động.'
        },

        {
            id: 48,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_03-00.jpg',
            img01: './assets/img/products/SU_KIEN_03-01.jpg',
            img02: './assets/img/products/SU_KIEN_03-02.jpg',
            img03: './assets/img/products/SU_KIEN_03-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 49,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_04-00.jpg',
            img01: './assets/img/products/SU_KIEN_04-01.jpg',
            img02: './assets/img/products/SU_KIEN_04-02.jpg',
            img03: './assets/img/products/SU_KIEN_04-03.jpg',
            img04: './assets/img/products/SU_KIEN_04-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 50,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_05-00.jpg',
            img01: './assets/img/products/SU_KIEN_05-01.jpg',
            img02: './assets/img/products/SU_KIEN_05-02.jpg',
            img03: './assets/img/products/SU_KIEN_05-03.jpg',
            img04: './assets/img/products/SU_KIEN_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },

        {
            id: 51,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_06-00.jpg',
            img01: './assets/img/products/SU_KIEN_06-01.jpg',
            img02: './assets/img/products/SU_KIEN_06-02.jpg',
            img03: './assets/img/products/SU_KIEN_06-03.jpg',
            img04: './assets/img/products/SU_KIEN_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 52,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_07-00.jpg',
            img01: './assets/img/products/SU_KIEN_07-01.jpg',
            img02: './assets/img/products/SU_KIEN_07-02.jpg',
            img03: './assets/img/products/SU_KIEN_07-03.jpg',
            img04: './assets/img/products/SU_KIEN_07-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 53,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_08-00.jpg',
            img01: './assets/img/products/SU_KIEN_08-01.jpg',
            img02: './assets/img/products/SU_KIEN_08-02.jpg',
            img03: './assets/img/products/SU_KIEN_08-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 54,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_09-00.jpg',
            img01: './assets/img/products/SU_KIEN_09-01.jpg',
            img02: './assets/img/products/SU_KIEN_09-02.jpg',
            img03: './assets/img/products/SU_KIEN_09-03.jpg',
            img04: './assets/img/products/SU_KIEN_09-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 55,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_10-00.jpg',
            img01: './assets/img/products/SU_KIEN_10-01.jpg',
            img02: './assets/img/products/SU_KIEN_10-02.jpg',
            img03: './assets/img/products/SU_KIEN_10-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 56,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_11-00.jpg',
            img01: './assets/img/products/SU_KIEN_11-01.jpg',
            img02: './assets/img/products/SU_KIEN_11-02.jpg',
            img03: './assets/img/products/SU_KIEN_11-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 57,
            status: 1, 
            title: 'Trang điểm sự kiện lung linh - cuốn hút',
            img: './assets/img/products/SU_KIEN_12-00.jpg',
            img01: './assets/img/products/SU_KIEN_12-01.jpg',
            img02: './assets/img/products/SU_KIEN_12-02.jpg',
            img03: './assets/img/products/SU_KIEN_12-03.jpg',
            img04: '',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Sự kiện',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        {
            id: 58,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_05-00.jpg',
            img01: './assets/img/products/KY_YEU_05-01.jpg',
            img02: './assets/img/products/KY_YEU_05-02.jpg',
            img03: './assets/img/products/KY_YEU_05-03.jpg',
            img04: './assets/img/products/KY_YEU_05-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        
        {
            id: 59,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_06-00.jpg',
            img01: './assets/img/products/KY_YEU_06-01.jpg',
            img02: './assets/img/products/KY_YEU_06-02.jpg',
            img03: './assets/img/products/KY_YEU_06-03.jpg',
            img04: './assets/img/products/KY_YEU_06-04.jpg',
            img05: '',
            img06: '',
            img07: '',
            img08: '',
            img09: '',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },
        
        {
            id: 60,
            status: 1, 
            title: 'Kỷ yếu tốt nghiệp quá chất',
            img: './assets/img/products/KY_YEU_07-00.jpg',
            img01: './assets/img/products/KY_YEU_07-01.jpg',
            img02: './assets/img/products/KY_YEU_07-02.jpg',
            img03: './assets/img/products/KY_YEU_07-03.jpg',
            img04: './assets/img/products/KY_YEU_07-04.jpg',
            img05: './assets/img/products/KY_YEU_07-05.jpg',
            img06: './assets/img/products/KY_YEU_07-06.jpg',
            img07: './assets/img/products/KY_YEU_07-07.jpg',
            img08: './assets/img/products/KY_YEU_07-08.jpg',
            img09: './assets/img/products/KY_YEU_07-09.jpg',
            img10: '',
            category: 'Kỷ yếu - Tốt nghiệp',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm chụp hình kỷ yếu - tốt nghiệp chất lắm người ơi, Lưu giữ mãi cái đẹp của tuổi trẻ - một thời không thể quên.'
        },

        {
            id: 61,
            status: 1, 
            title: 'Mẫu ảnh cuốn hút',
            img: './assets/img/products/MAU_ANH_21-00.jpg',
            img01: './assets/img/products/MAU_ANH_21-01.jpg',
            img02: './assets/img/products/MAU_ANH_21-02jpg',
            img03: './assets/img/products/MAU_ANH_21-03.jpg',
            img04: './assets/img/products/MAU_ANH_21-04.jpg',
            img05: './assets/img/products/MAU_ANH_21-05.jpg',
            img06: './assets/img/products/MAU_ANH_21-06.jpg',
            img07: './assets/img/products/MAU_ANH_21-07.jpg',
            img08: './assets/img/products/MAU_ANH_21-08.jpg',
            img09: './assets/img/products/MAU_ANH_21-09.jpg',
            img10: './assets/img/products/MAU_ANH_21-10.jpg',
            img11: './assets/img/products/MAU_ANH_21-11.jpg',
            img12: './assets/img/products/MAU_ANH_21-12.jpg',
            img13: './assets/img/products/MAU_ANH_21-13.jpg',
            video: './assets/video/MAU_ANH_21.mp4',
            category: 'Mẫu ảnh - Thời trang',
            MUA: 'Trịnh Văn Phi Long',
            price: 500000,
            desc: 'Trang điểm mẫu ảnh, chụp ảnh thời trang lữu giữ mãi thời thanh xuân xinh đẹp.'
        },
        
        ]
        localStorage.setItem('products', JSON.stringify(products));
    }
}

// Create admin account 
function createAdminAccount() {
    let accounts = localStorage.getItem("accounts");
    if (!accounts) {
        accounts = [];
        accounts.push({
            fullname: "Hoàng Gia Bảo",
            phone: "hgbaodev",
            password: "123456",
            address: 'https://github.com/hgbaodev',
            email: 'musicanime2501@gmail.com',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        accounts.push({
            fullname: "Trần Nhật Sinh",
            phone: "0123456789",
            password: "123456",
            address: '',
            email: '',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        localStorage.setItem('accounts', JSON.stringify(accounts));
    }
}

window.onload = createProduct();
window.onload = createAdminAccount();